config/routes.rb
TeamMate::Application.routes.draw do

  resources :people

  resources :projects do
    resources :tasks do
      resources :task_journals
    end
    get '/root_wiki', :controller => 'wikis', :action => 'root'
    get '/wiki/:id/edit', :controller => 'wikis', :action => 'edit', :as => 'edit_wiki'
    get '/wiki/:parent_id/:subject', :controller => 'wikis', :action => 'show_or_new', :as => 'show_or_new_wiki'
    post '/wikis', :controller => 'wikis', :action => 'create'
    patch '/wiki/:id', :controller => 'wikis', :action => 'update', :as => 'wiki'
    delete '/wiki/:id', :controller => 'wikis', :action => 'destroy'
  end

  get '/my_tasks/(:type)', :controller => 'people', :action => 'tasks', :as => :my_tasks
  get '/my_activities', :controller => 'people', :action => 'activities', :as => :my_activities

  devise_for :users, :controllers => {
    :sessions => 'auth/sessions',
    :passwords => 'auth/passwords',
    :registrations => 'auth/registrations'
  }

  root :to => "people#tasks"

end

app/models/person.rb
class Person < ActiveRecord::Base
  module Role
    ADMIN = :admin
    MANAGER = :manager
    NORMAL = :normal
    OPTIONS = [ADMIN, MANAGER, NORMAL]
  end
  self.table_name = 'users'

  validates :name, :presence => true, :length => {:maximum => 200}, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true
  validates :role, :presence => true
  validates :encrypted_password, :presence => true, :if => Proc.new {|person| person.new_record?}
  validates :encrypted_password ,:length => { :in => 8..200 }
  validates :encrypted_password, :confirmation => true
  #validates :encrypyed_password_confirmation, :presence => true

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  before_action :set_nav_item_name, :except => [:tasks, :activities]

  before_action do |controller|
    actions = ['edit', 'update', 'destroy']
    return unless actions.include? action_name
    role = current_user.role
    if role == 'admin'
      if @person.role == 'admin'
        redirect_to people_path, :alert => '访问被拒绝，您可能没有权限或未登录。'
        return
      end
    elsif role == 'manager'
      if ['admin', 'manager'].include? @person.role
        redirect_to people_path, :alert => '访问被拒绝，您可能没有权限或未登录。'
        return
      end
    end
  end


  def tasks
    search_condition = case params[:search_key]
                         when 'subject'
                           Task.where('subject like ?', "%#{params[:search_value]}%")
                         when 'id'
                           Task.where(:id => params[:search_value].to_i)
                         when 'parent_subject'
                           Task.joins(:parent).where('parents_tasks.subject like ?', "%#{params[:search_value]}%")
                         when 'parent_id'
                           Task.joins(:parent).where('parents_tasks.id = ?', params[:search_value].to_i)
                         when 'category'
                           categories = {
                             "Bug修复" => :bug_fixing,
                             "新增功能" => :new_feature,
                             "支持" => :support
                           }
                           category = params[:search_value]
                           matched_categories = []
                           categories.each_pair do |k, v|
                             if k.include? category
                               matched_categories << v
                             end
                           end
                           Task.where(:category => matched_categories)
                         when 'priority'
                           Task.where :priority => params[:search_value].to_i
                         when 'project'
                           Task.joins(:project).where('projects.name like ?', "%#{params[:search_value]}%")
                       end

    @type = params[:type]


    if @type and @type == 'watching'
      @tasks = current_user.watching_tasks.merge(search_condition).page params[:page]
    else
      @type = :assigned_to
      @tasks = current_user.tasks.merge(search_condition).page params[:page]
    end
    @nav_item_name = 'my-tasks'

    @search_form = {
      :path => my_tasks_path(@type),
      :search_value => params[:search_value] || '',
      :search_key => (params[:search_key]  || :subject).to_sym,
      :key_options => {
        :subject => '主题',
        :id => 'ID',
        :parent_subject => '父任务主题',
        :parent_id => '父任务ID',
        :category => '分类',
        :priority => '优先级',
        :project => '项目名称',
      }
    }.with_indifferent_access
  end

  def activities
    search_condition = case params[:search_key]
                         when 'subject'
                           TaskJournal.joins(:task).where('subject like ?', "%#{params[:search_value]}%")
                         when 'project'
                           TaskJournal.joins(:task => :project).where('projects.name like ?', "%#{params[:search_value]}%")
                       end
    @journals = current_user.task_activities.merge(search_condition).page params[:page]
    @type = :activities
    @nav_item_name = 'my-tasks'
    @search_form = {
      :path => my_activities_path,
      :search_value => params[:search_value] || '',
      :search_key => (params[:search_key]  || :subject).to_sym,
      :key_options => {
        :subject => '主题',
        :project => '项目名称',
      }
    }.with_indifferent_access
  end

  # GET /people
  # GET /people.json
  def index

    search_condition = case params[:search_key]
                         when 'name'
                           Person.where('name like ?', "%#{params[:search_value]}%")
                         when 'id'
                           Person.where(:id => params[:search_value].to_i)
                         when 'email'
                           Person.where('email like ?', "%#{params[:search_value]}%")
                         when 'role'
                           roles = {
                             '管理员' => :admin,
                             '部门经理' => :manager,
                             '普通用户' => :normal
                           }
                           role = params[:search_value]
                           matched_roles = []
                           roles.each_pair do |k, v|
                             if k.include? role
                               matched_roles << v
                             end
                           end
                           Person.where(:role => matched_roles)
                         else
                           Person.all
                       end
    @people = search_condition.page(params[:page])

    @search_form = {
      :path => people_path,
      :search_value => params[:search_value] || '',
      :search_key => (params[:search_key]  || :name).to_sym,
      :key_options => {
        :name => '用户名',
        :id => 'ID',
        :email => 'Email',
        :role => '角色'
      }
    }.with_indifferent_access
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
    @person.role = Person::Role::NORMAL
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)
    current_user_role = current_user.role
    person_role = person_params[:role]
    if current_user_role == 'admin'
      if person_role == 'admin'
        @person.errors.add :role, '您所创建的用户必须低于您的角色级别'
      end
    else
      if ['admin', 'manager'].include? person_role
        @person.errors.add :role, '您所创建的用户必须低于您的角色级别'
      end
    end

    if @person.errors.any?
      respond_to do |format|
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
      return
    end

    respond_to do |format|
      if @person.save
        encrypted_password = Devise.bcrypt(Class.new do
          class << self
            Devise::Models.config self, :pepper, :stretches
          end
        end, person_params[:encrypted_password])
        @person.update :encrypted_password => encrypted_password, :encrypted_password_confirmation => encrypted_password
        unless @person.locked
          UserMailer.account_created(User.find(@person.id), person_params[:encrypted_password]).deliver
        end
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update

    current_user_role = current_user.role
    person_role = person_params[:role]
    if current_user_role == 'admin'
      if person_role == 'admin'
        @person.errors.add :role, '您所创建的用户必须低于您的角色级别'
      end
    else
      if ['admin', 'manager'].include? person_role
        @person.errors.add :role, '您所创建的用户必须低于您的角色级别'
      end
    end

    if @person.errors.any?
      respond_to do |format|
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
      return
    end

    original_locking_status = @person.locked
    params = person_params
    unless params[:encrypted_password].present?
      params.delete :encrypted_password
      params.delete :encrypted_password_confirmation
    end
    respond_to do |format|
      if @person.update(params)
        if params[:encrypted_password]
          encrypted_password = Devise.bcrypt(Class.new do
            class << self
              Devise::Models.config self, :pepper, :stretches
            end
          end, params[:encrypted_password])
          @person.update :encrypted_password => encrypted_password, :encrypted_password_confirmation => encrypted_password
          UserMailer.password_changed(User.find(@person.id), params[:encrypted_password]).deliver
        end
        if original_locking_status and ! @person.locked
          UserMailer.account_unlocked(User.find @person.id).deliver
        end
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    def set_nav_item_name
      @nav_item_name = 'management'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :email, :encrypted_password, :encrypted_password_confirmation, :role, :avatar, :locked)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= simple_form_for @person, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :encrypted_password %>
  <%= f.input :encrypted_password_confirmation %>
  <%= f.input :role, :collection => Person::Role::OPTIONS, :input_html => {:class => 'chosen-select'} %>
  <%= f.input :locked %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                people_path, :class => 'btn btn-default' %>
<% end %>

app/views/people/activities.html.erb
<% model_class = TaskJournal %>

<div class="nav-tabs">
  <%= render :partial => "common/my_tasks_tabs", :locals => {:tab_name => @type} %>
</div>
<div class="row" style="padding-top: 40px">
  <%= search_form_for @search_form %>
</div>
<hr/>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:project) %></th>
    <th><%= model_class.human_attribute_name(:task) %></th>
    <th><%= model_class.human_attribute_name(:time_entry_hours) %></th>
    <th><%= model_class.human_attribute_name(:old_done_ratio) %> ID</th>
    <th><%= model_class.human_attribute_name(:new_done_ratio) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
  </tr>
  </thead>
  <tbody>
  <% @journals.each do |journal| %>
      <tr>
        <td><%= journal.id %></td>
        <td><%= link_to journal.task.project.name, project_tasks_path(journal.task.project) %></td>
        <td><%= link_to journal.task.subject, project_task_path(journal.task.project, journal.task) %></td>
        <td><%= journal.time_entry_hours %> 小时</td>
        <td style="width: 200px">
          <div class="progress" style="margin-bottom: 0px">
            <span class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="<%= journal.old_done_ratio %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= journal.old_done_ratio %>%">
              <span><%= journal.old_done_ratio %>%</span>
            </span>
          </div>
        </td>
        <td style="width: 200px">
          <div class="progress" style="margin-bottom: 0px">
            <span class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="<%= journal.new_done_ratio %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= journal.new_done_ratio %>%">
              <span><%= journal.new_done_ratio %>%</span>
            </span>
          </div>
        </td>
        <td><%=time_ago_in_words journal.created_at %>前</td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="row">
  <div class="col-lg-12">
    <div class="pull-right">
      <%= paginate @journals %>
    </div>
  </div>
</div>

app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="nav-tabs">
  <%= render :partial => "common/manage_module_tabs", :locals => {:tab_name => 'users'} %>
</div>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', '编辑%{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<%- model_class = Person -%>

<div class="nav-tabs">
  <%= render :partial => "common/manage_module_tabs", :locals => {:tab_name => 'users'} %>
</div>
<div class="row" style="padding-top: 40px">
  <%= search_form_for @search_form %>
</div>
<hr/>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:avatar) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:role) %></th>
      <th><%= model_class.human_attribute_name(:locked) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><img class="img-circle" width="30" height="30" src="<%= avatar_path(person) %>"/></td>
        <td><%= link_to person.name || '', person_path(person) %></td>
        <td><%= link_to person.email, person_path(person) %></td>
        <td><%=t person.role, :scope => 'simple_form.options.person.role', :default => "" %></td>
        <td><%= person.locked ? '是' : '否' %></td>
        <td><%= person.current_sign_in_at and l person.current_sign_in_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_path(person), :class => "btn btn-default btn-xs #{"disabled" unless role_level_lt_me(person)}"  %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_path(person),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => "btn btn-xs btn-danger #{"disabled" unless role_level_lt_me(person)}" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <div class="col-lg-12">
    <div class="pull-right">
      <%= paginate @people%>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_person_path,
            :class => 'btn btn-primary' %>
  </div>
</div>

app/views/people/new.html.erb
<%- model_class = Person -%>

<div class="nav-tabs">
  <%= render :partial => "common/manage_module_tabs", :locals => {:tab_name => 'users'} %>
</div>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', '新建%{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
<%- model_class = Person -%>
<div class="nav-tabs">
  <%= render :partial => "common/manage_module_tabs", :locals => {:tab_name => 'users'} %>
</div>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>


<img class="img-circle" width="200" height="200" src="<%= avatar_path @person %>"/>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @person.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @person.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:role) %>:</strong></dt>
  <dd><%=t @person.role, :scope => 'simple_form.options.person.role' %></dd>
  <dt><strong><%= model_class.human_attribute_name(:locked) %>:</strong></dt>
  <dd><%= @person.locked ? '是' : '否' %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              people_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_person_path(@person), :class => "btn btn-default #{"disabled" unless role_level_lt_me(@person)}" %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_path(@person),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => "btn btn-danger #{"disabled" unless role_level_lt_me(@person)}" %>

app/views/people/tasks.html.erb
<% model_class = Task %>

<div class="nav-tabs">
  <%= render :partial => "common/my_tasks_tabs", :locals => {:tab_name => @type} %>
</div>
<div class="row" style="padding-top: 40px">
  <%= search_form_for @search_form %>
</div>
<hr/>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:project) %></th>
    <th><%= model_class.human_attribute_name(:subject) %></th>
    <th><%= model_class.human_attribute_name(:parent) %> ID</th>
    <th><%= model_class.human_attribute_name(:category) %></th>
    <th><%= model_class.human_attribute_name(:priority) %></th>
    <th><%= model_class.human_attribute_name(:assigned_to_user) %></th>
    <th><%= model_class.human_attribute_name(:time_entry_hours) %></th>
    <th><%= model_class.human_attribute_name(:ratio) %></th>
    <th><%= model_class.human_attribute_name(:at_risk) %></th>
    <th><%= model_class.human_attribute_name(:updated_at) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.id, [task.project, task] %></td>
        <td><%= link_to task.project.name, project_tasks_path(task.project) %></td>
        <td><%= link_to task.subject, [task.project, task] %></td>
        <td><%= task.parent.present? ? link_to(task.parent.id, [task.project, task.parent]) : "" %></td>
        <td><%= t task.category, :scope => 'simple_form.options.task.category' %></td>
        <td><%= task.priority %></td>
        <td>
          <span class="label label-primary">
            <%= task.assigned_to_user.name %>
          </span>
        </td>
        <td><%= task.time_entry_hours %> 小时</td>
        <td style="width: 200px">
          <div class="progress" style="margin-bottom: 0px">
            <span class="progress-bar progress-bar-<%= task.at_risk ? 'danger' : 'success' %>" role="progressbar" aria-valuenow="<%= task.ratio %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= task.ratio %>%">
              <span><%= task.ratio %>%</span>
            </span>
          </div>
        </td>
        <td><%= task.at_risk ? '是' : '否' %></td>
        <td><%=l task.updated_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_task_path(task.project, task), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      [task.project, task],
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<div class="row">
  <div class="col-lg-12">
    <div class="pull-right">
      <%= paginate @tasks %>
    </div>
  </div>
</div>