config/routes.rb
TeamMate::Application.routes.draw do

  resources :people

  resources :projects do
    resources :tasks do
      resources :task_journals
    end
    get '/root_wiki', :controller => 'wikis', :action => 'root'
    get '/wiki/:id/edit', :controller => 'wikis', :action => 'edit', :as => 'edit_wiki'
    get '/wiki/:parent_id/:subject', :controller => 'wikis', :action => 'show_or_new', :as => 'show_or_new_wiki'
    post '/wikis', :controller => 'wikis', :action => 'create'
    patch '/wiki/:id', :controller => 'wikis', :action => 'update', :as => 'wiki'
    delete '/wiki/:id', :controller => 'wikis', :action => 'destroy'
  end

  get '/my_tasks/(:type)', :controller => 'people', :action => 'tasks', :as => :my_tasks
  get '/my_activities', :controller => 'people', :action => 'activities', :as => :my_activities

  devise_for :users, :controllers => {
    :sessions => 'auth/sessions',
    :passwords => 'auth/passwords',
    :registrations => 'auth/registrations'
  }

  root :to => "people#tasks"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :managers, :class_name => 'User', :join_table => 'managers_projects'
  has_and_belongs_to_many :members, :class_name => 'User', :join_table => 'members_projects'
  has_many :wikis
  has_many :tasks

  validates :name, :presence => true, :length => {:maximum => 200}
  validates :managers, :presence => true

  def self.projects_of(user)
    if user.role == 'admin'
      all
    else
      (user.managed_projects + user.involved_projects).uniq
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  before_action :set_nav_item_name

  before_action do |controller|
    actions = ['edit', 'updtae', 'destroy']
    return unless actions.include? action_name
    role = current_user.role
    project = Project.find params[:id]
    unless role == 'admin' or project.managers.all.include? current_user
      redirect_to projects_path, :alert => '访问被拒绝，您可能没有权限或未登录。'
    end
  end

  # GET /projects
  # GET /projects.json
  def index

    search_condition = case params[:search_key]
                         when 'name'
                           Project.where('name like ?', "%#{params[:search_value]}%")
                         when 'id'
                           Project.where(:id => params[:search_value].to_i)
                         when 'manager'
                           Project.joins(:managers).where('users.name like ?', "%#{params[:search_value]}%").uniq
                       end

    if current_user.role == 'admin'
      @projects = Project.page.merge(search_condition).page(params[:page])
    else
      @projects = current_user.managed_projects.merge(search_condition).page(params[:page])
    end

    @search_form = {
      :path => projects_path,
      :search_value => params[:search_value] || '',
      :search_key => (params[:search_key]  || :name).to_sym,
      :key_options => {
        :name => '名称',
        :id => 'ID',
        :manager => '管理员'
      }
    }.with_indifferent_access
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.managers << current_user
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def set_nav_item_name
      @nav_item_name = 'management'
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :public, :manager_ids => [], :member_ids => [])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description, :input_html => {:rows => 10} %>
  <%= f.input :public %>
  <%= f.association :managers, :collection => User.all, :input_html => {:class => 'chosen-select'} %>
  <%= f.association :members, :collection => User.all, :input_html => {:class => 'chosen-select'} %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn btn-default' %>
<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="nav-tabs">
  <%= render :partial => "common/manage_module_tabs", :locals => {:tab_name => 'projects'} %>
</div>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', '编辑%{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="nav-tabs">
  <%= render :partial => "common/manage_module_tabs", :locals => {:tab_name => 'projects'} %>
</div>
<div class="row" style="padding-top: 40px">
  <%= search_form_for @search_form %>
</div>
<hr/>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:public) %></th>
      <th><%= model_class.human_attribute_name(:managers) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.id, project_path(project) %></td>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= project.public ? '是' : '否' %></td>
        <td>
        <% project.managers.each do |m| %>
          <span class="label label-primary"><%= m.name %></span>
        <% end %>
        </td>
        <td><%=l project.updated_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <div class="col-lg-12">
    <div class="pull-right">
      <%= paginate @projects %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>
  </div>
</div>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="nav-tabs">
  <%= render :partial => "common/manage_module_tabs", :locals => {:tab_name => 'projects'} %>
</div>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', '新建%{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="nav-tabs">
  <%= render :partial => "common/manage_module_tabs", :locals => {:tab_name => 'projects'} %>
</div>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>


<div class="panel panel-primary">
  <div class="panel-heading">
    基本信息
  </div>
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
      <dd><%= @project.name %></dd>
      <dt><strong><%= model_class.human_attribute_name(:public) %>:</strong></dt>
      <dd><%= @project.public ? '是' : '否' %></dd>
      <dt><strong><%= model_class.human_attribute_name(:managers) %>:</strong></dt>
      <dd>
      <% @project.managers.each do |m| %>
          <span class="label label-primary"><%= m.name %></span>
      <% end %>
      </dd>
      <dd>
      <dt><strong><%= model_class.human_attribute_name(:members) %>:</strong></dt>
      <% @project.members.each do |m| %>
          <span class="label label-default"><%= m.name %></span>
      <% end %>
      </dd>
    </dl>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    描述
  </div>
  <div class="panel-body">
    <%=markdown @project.description %>
  </div>
</div>


<%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_path(@project), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_path(@project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>