config/routes.rb
TeamMate::Application.routes.draw do

  resources :people

  resources :projects do
    resources :tasks do
      resources :task_journals
    end
    get '/root_wiki', :controller => 'wikis', :action => 'root'
    get '/wiki/:id/edit', :controller => 'wikis', :action => 'edit', :as => 'edit_wiki'
    get '/wiki/:parent_id/:subject', :controller => 'wikis', :action => 'show_or_new', :as => 'show_or_new_wiki'
    post '/wikis', :controller => 'wikis', :action => 'create'
    patch '/wiki/:id', :controller => 'wikis', :action => 'update', :as => 'wiki'
    delete '/wiki/:id', :controller => 'wikis', :action => 'destroy'
  end

  get '/my_tasks/(:type)', :controller => 'people', :action => 'tasks', :as => :my_tasks
  get '/my_activities', :controller => 'people', :action => 'activities', :as => :my_activities

  devise_for :users, :controllers => {
    :sessions => 'auth/sessions',
    :passwords => 'auth/passwords',
    :registrations => 'auth/registrations'
  }

  root :to => "people#tasks"

end

app/views/common/_manage_module_tabs.html.erb
<ul id="manage-module-tabs" class="nav nav-tabs nav-justified">
  <li id="tab-projects">
    <%= link_to '项目管理', projects_path %>
  </li>
  <li id="tab-users">
    <%= link_to '用户管理', people_path %>
  </li>
</ul>
<script type="text/javascript">
  $('#manage-module-tabs li').removeClass('active');
  var tab_name = '<%= tab_name %>';
  $('#tab-' + tab_name).addClass('active')
</script>

app/views/common/_my_tasks_tabs.html.erb
<ul id="my-tasks-tabs" class="nav nav-tabs nav-justified">
  <li id="tab-assigned_to">
    <%= link_to '指派给我的任务', my_tasks_path(:assigned_to) %>
  </li>
  <li id="tab-watching">
    <%= link_to '我跟踪的任务', my_tasks_path(:watching) %>
  </li>
  <li id="tab-activities">
    <%= link_to '我的活动', my_activities_path %>
  </li>
</ul>
<script type="text/javascript">
    $('#my-tasks-tabs li').removeClass('active');
    var tab_name = '<%= tab_name %>';
    $('#tab-' + tab_name).addClass('active')
</script>

app/views/common/_project_module_tabs.html.erb
<ul id="project-module-tabs" class="nav nav-tabs nav-justified">
  <li id="tab-tasks">
    <%= link_to '任务', project_tasks_path %>
  </li>
  <li id="tab-wikis">
    <%= link_to 'Wikis', project_root_wiki_path(@project) %>
  </li>
</ul>
<script type="text/javascript">
  $('#project-module-tabs li').removeClass('active');
  var tab_name = '<%= tab_name %>';
  $('#tab-' + tab_name).addClass('active')
</script>