config/routes.rb
TeamMate::Application.routes.draw do

  resources :people

  resources :projects do
    resources :tasks do
      resources :task_journals
    end
    get '/root_wiki', :controller => 'wikis', :action => 'root'
    get '/wiki/:id/edit', :controller => 'wikis', :action => 'edit', :as => 'edit_wiki'
    get '/wiki/:parent_id/:subject', :controller => 'wikis', :action => 'show_or_new', :as => 'show_or_new_wiki'
    post '/wikis', :controller => 'wikis', :action => 'create'
    patch '/wiki/:id', :controller => 'wikis', :action => 'update', :as => 'wiki'
    delete '/wiki/:id', :controller => 'wikis', :action => 'destroy'
  end

  get '/my_tasks/(:type)', :controller => 'people', :action => 'tasks', :as => :my_tasks
  get '/my_activities', :controller => 'people', :action => 'activities', :as => :my_activities

  devise_for :users, :controllers => {
    :sessions => 'auth/sessions',
    :passwords => 'auth/passwords',
    :registrations => 'auth/registrations'
  }

  root :to => "people#tasks"

end

app/models/task_journal.rb
class TaskJournal < ActiveRecord::Base
  belongs_to :task
  belongs_to :operator, :class_name => 'User'

  validates :time_entry_hours, :presence => true
  validates :time_entry_hours, :numericality => {:only_integer => true}, :allow_blank => true
  validates :new_done_ratio, :presence => true
  validates :new_done_ratio, :numericality => {:only_integer => true, :less_than_or_equal_to => 100}, :allow_blank => true
end

app/controllers/task_journals_controller.rb
class TaskJournalsController < ApplicationController
  before_action :set_task_journal, only: [:show, :edit, :update, :destroy]

  # GET /task_journals
  # GET /task_journals.json
  def index
    @task_journals = TaskJournal.all
  end

  # GET /task_journals/1
  # GET /task_journals/1.json
  def show
  end

  # GET /task_journals/new
  def new
    @task_journal = TaskJournal.new
  end

  # GET /task_journals/1/edit
  def edit
  end

  # POST /task_journals
  # POST /task_journals.json
  def create
    @project = Project.find params[:project_id]
    @task = Task.find params[:task_id]
    @task_journal = @task.task_journals.build(task_journal_params)
    @task_journal.operator_id = current_user.id
    @task_journal.old_done_ratio = @task.ratio

    respond_to do |format|
      if @task_journal.save
        @task.update :ratio => @task_journal.new_done_ratio,
                     :time_entry_hours => @task.time_entry_hours + task_journal_params[:time_entry_hours].to_i
        UserMailer.task_changed(@task_journal).deliver
        format.html { redirect_to [@project, @task], notice: 'Task journal was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@project, @task] }
      else
        format.html { render action: 'new' }
        format.json { render json: @task_journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_journals/1
  # PATCH/PUT /task_journals/1.json
  def update
    respond_to do |format|
      if @task_journal.update(task_journal_params)
        format.html { redirect_to @task_journal, notice: 'Task journal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task_journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_journals/1
  # DELETE /task_journals/1.json
  def destroy
    @task_journal.destroy
    respond_to do |format|
      format.html { redirect_to task_journals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_journal
      @task_journal = TaskJournal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_journal_params
      params.require(:task_journal).permit(:time_entry_hours, :old_done_ratio, :new_done_ratio, :task_id, :operator_id)
    end
end

app/helpers/task_journals_helper.rb
module TaskJournalsHelper
end

app/views/task_journals/_form.html.erb
<%= simple_form_for @task_journal, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :time_entry_hours %>
  <%= f.input :old_done_ratio %>
  <%= f.input :new_done_ratio %>
  <%= f.input :task_id %>
  <%= f.input :operator_id %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                task_journals_path, :class => 'btn btn-default' %>
<% end %>

app/views/task_journals/edit.html.erb
<%- model_class = TaskJournal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/task_journals/index.html.erb
<%- model_class = TaskJournal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:time_entry_hours) %></th>
      <th><%= model_class.human_attribute_name(:old_done_ratio) %></th>
      <th><%= model_class.human_attribute_name(:new_done_ratio) %></th>
      <th><%= model_class.human_attribute_name(:task_id) %></th>
      <th><%= model_class.human_attribute_name(:operator_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @task_journals.each do |task_journal| %>
      <tr>
        <td><%= link_to task_journal.id, task_journal_path(task_journal) %></td>
        <td><%= task_journal.time_entry_hours %></td>
        <td><%= task_journal.old_done_ratio %></td>
        <td><%= task_journal.new_done_ratio %></td>
        <td><%= task_journal.task_id %></td>
        <td><%= task_journal.operator_id %></td>
        <td><%=l task_journal.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_task_journal_path(task_journal), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      task_journal_path(task_journal),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_task_journal_path,
            :class => 'btn btn-primary' %>

app/views/task_journals/new.html.erb
<%- model_class = TaskJournal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/task_journals/show.html.erb
<%- model_class = TaskJournal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:time_entry_hours) %>:</strong></dt>
  <dd><%= @task_journal.time_entry_hours %></dd>
  <dt><strong><%= model_class.human_attribute_name(:old_done_ratio) %>:</strong></dt>
  <dd><%= @task_journal.old_done_ratio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:new_done_ratio) %>:</strong></dt>
  <dd><%= @task_journal.new_done_ratio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:task_id) %>:</strong></dt>
  <dd><%= @task_journal.task_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:operator_id) %>:</strong></dt>
  <dd><%= @task_journal.operator_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              task_journals_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_task_journal_path(@task_journal), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              task_journal_path(@task_journal),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>